// K8 Dapr Endpoint 
@baseUrlDapr =  https://trafficcontrolservice.wonderfulwater-88ac0d11.eastus.azurecontainerapps.io
@baseUrl =  https://trafficcontrolservice.wonderfulwater-88ac0d11.eastus.azurecontainerapps.io

// K8 Direct Endpoint
#@baseUrl =  http://20.241.231.194
#@baseUrlDapr =  http://20.241.231.205

// Status
GET {{baseUrl}}/status

###

// Status Dapr
GET {{baseUrlDapr}}/v1.0/invoke/trafficcontrolservice/method/status

###

// Status Dapr
GET {{baseUrlDapr}}/v1.0/healthz

###

// Register entry
POST {{baseUrl}}/entrycam
Content-Type: application/json

{ "lane": 1, "licenseNumber": "XT-346-YZ", "timestamp": "2022-09-20T10:38:47" }

###

// Register exit
POST {{baseUrl}}/exitcam
Content-Type: application/json

{ "lane": 1, "licenseNumber": "XT-346-YZ", "timestamp": "2022-09-20T10:38:51" }



###

GET {{baseUrlDapr}}/v1.0/secrets/secret-store/dapr-traffic-control-iothub