// K8 Dapr Endpoint 
@baseUrlDapr =  http://20.85.253.155

//@baseUrl =  http://127.0.0.1:6000

// K8 Direct Endpoint
@baseUrl =  http://20.237.16.204

// Status
GET {{baseUrl}}/status

###

// Status Dapr
GET {{baseUrlDapr}}/v1.0/invoke/trafficcontrolservice/method/status

###

// Status Dapr
GET {{baseUrlDapr}}/v1.0/healthz

###

// Register entry
POST {{baseUrl}}/entrycam
Content-Type: application/json

{ "lane": 1, "licenseNumber": "XT-346-Y", "timestamp": "2020-09-10T10:38:47" }

###

// Register exit
POST {{baseUrl}}/exitcam
Content-Type: application/json

{ "lane": 1, "licenseNumber": "XT-346-Y", "timestamp": "2020-09-10T10:38:52" }



###

GET {{baseUrlDapr}}/v1.0/secrets/secret-store/dapr-traffic-control