// K8 Dapr Endpoint 
@baseUrlDapr =  http://20.81.59.37

//@baseUrl =  http://127.0.0.1:6000

// K8 Direct Endpoint
@baseUrl =  http://20.241.231.205
@baseUrlDapr =  http://20.241.231.194

// Status
GET {{baseUrl}}/status

###

// Status Dapr
GET {{baseUrlDapr}}/v1.0/invoke/trafficcontrolservice/method/status

###

// Status Dapr
GET {{baseUrlDapr}}/v1.0/healthz

###

// Register entry
POST {{baseUrl}}/entrycam
Content-Type: application/json

{ "lane": 1, "licenseNumber": "XT-346-YZ", "timestamp": "2022-07-20T10:38:47" }

###

// Register exit
POST {{baseUrl}}/exitcam
Content-Type: application/json

{ "lane": 1, "licenseNumber": "XT-346-YZ", "timestamp": "2022-07-20T10:38:50" }



###

GET {{baseUrlDapr}}/v1.0/secrets/secret-store/dapr-traffic-control-iothub