apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
namespace: dapr-traffic-control
resources:
 - dapr-component-binding-http-mail.yml
 - dapr-component-pubsub-servicebus.yml
 - dapr-component-pubsub-subscription.yml
 - dapr-component-secrets.yml
 - dapr-component-secrets-akv.yml
 - dapr-component-state-redis.yml
 - deployment-FineCollectionService.yaml
 - deployment-TrafficControlService.yaml
 - deployment-VehicleRegistrationService.yaml
 - k8-secret-rbac.yml
 
