
@baseUrl = http://20.242.195.103

// Status Dapr
GET {{baseUrl}}/v1.0/invoke/vehicleregistrationservice/method/status

###

// Get vehicle info by license-number DAPR
GET {{baseUrl}}/v1.0/invoke/vehicleregistrationservice/method/vehicleinfo/KZ-49-VX


###

GET {{baseUrl}}/v1.0/secrets/secret-store/dapr-traffic-control-iothub