@baseUrl =  https://vehicleregistrationservice.agreeableforest-837b7d25.eastus.azurecontainerapps.io
@baseUrlAks = http://20.232.70.91

// Get vehicle info by license-number
GET {{baseUrl}}/vehicleinfo/KZ-49-VX


###

// Get vehicle info by license-number DAPR
GET {{baseUrlAks}}/v1.0/invoke/vehicleregistrationservice/method/vehicleinfo/KZ-49-VX