// Get vehicle info by license-number
GET http://127.0.0.1:6002/vehicleinfo/KZ-49-VX


###

// Get vehicle info by license-number DAPR
GET http://localhost:3601/v1.0/invoke/vehicleregistrationservice/method/vehicleinfo/KZ-49-VX

