@baseUrl =  https://localhost:44335

// Status
GET {{baseUrl}}/status

###

// Publish speeding violation
POST {{baseUrl}}/collectfine
Content-Type: application/json

{ "vehicleId": "RT-318-K", "roadId": "A12", "violationInKmh": 15, "timestamp": "2020-09-20T08:33:41" }

###

POST http://localhost:3601/v1.0/invoke/finecollectionservice/method/collectfine
Content-Type: application/json

{ "vehicleId": "RT-318-K", "roadId": "A12", "violationInKmh": 15, "timestamp": "2020-09-20T08:33:41" }